# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20160617_1625'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to='login_registration.User'),
        ),
    ]
