# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20160617_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.SmallIntegerField(default=9),
            preserve_default=False,
        ),
    ]
