# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
